### ISSUE TITLE
Add support for elasticsearch

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#103]
This might be overkill, but it's probably worth exploring to see if it's hard to do or not. The [ElasticPress](https://github.com/10up/ElasticPress) has some pretty extensive documentation. DebOps has a role for it, but it seems outdated so we might have to create our own.

**Comment by tobeycodes** [comment]
Do you think there reaches a point where it's better to put something like this on it's own dedicated server?

Either way it should be pretty straightforward to setup. With AWS elastic search instance ElasticPress works straight out of the box. The only issues I've had with it before is indexing, but that's due to WordPress crons and how bad they are.

**Comment by blindpet** [comment]
@carlalexander you should be able to create an updated role for it from [this](https://guides.wp-bullet.com/install-configure-elasticsearch-to-speed-up-wordpress-search/)

@schrapel at some point it is but you need a pretty big site to justify it in my experience

**Comment by carlalexander** [comment]
Thanks! I'll look into that @blindpet! As for whether this is too much for one server, we'll see! My guess is that it shouldn't be too much. Most WordPress sites don't have that much content to index. I'm interested in adding it because it offers better search capabilities.

**Comment by carlalexander** [comment]
Thanks to @schrapel, we now have support for elasticsearch. The [recommended plugins wiki page](https://github.com/carlalexander/debops-wordpress/wiki/Recommended-plugins) is updated with details on how to configure the ElasticPress plugin.
