### ISSUE TITLE
error installing Ansible and DebOps

### ISSUE THREAD

**Issue by Lylasz** [carlalexander/debops-wordpress#104]
When I run: "sudo pip install ansible debops passlib pycrypto" I get the following error at the end. I am new to all of this and trying to learn as I go but I couldn't find out how to solve this myself. Could anyone help me?

Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip_build       _root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file       __).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-       bB9fNe-record/install-record.txt --single-version-externally-managed --compile f       ailed with error code 1 in /tmp/pip_build_root/cryptography
Storing debug log for failure in /root/.pip/pip.log

**Comment by carlalexander** [comment]
I've never seen this error before. What operating system are you running the command on?

**Comment by cristianls** [comment]
Same here. Ubuntu 16.04

**Comment by carlalexander** [comment]
I've just gone through the install process on a new Mac. I didn't run into issues. Only thing I can think of is maybe I should add these commands first?

```
$ pip install --upgrade setuptools
$ pip install --upgrade pip
```

**Comment by ejholdings** [comment]
I'm getting the exact same problem.

I'm using a Digital Ocean VM with Ubuntu 16.04.1 (Xenial).  It is the vanilla VM -- I don't know Linux so I am following your walkthrough exactly as it is written.

Any ideas or suggestions would be greatly appreciated!  Here is a screen grab of my terminal showing both the error and the version of the OS.

![err_ubuntu](https://cloud.githubusercontent.com/assets/25045872/21831821/53a75f7e-d76c-11e6-8521-2870b45079de.png)

**Comment by carlalexander** [comment]
I can also reproduce the issue. Let me investigate and get back to you 😃

**Comment by ejholdings** [comment]
The problem is somehow related to installing ansible.  If I use this code instead, I have no problems at all (please forgive the // for my comments -- I'm so clueless with linux that I don't know if that is the right character for comments or not in Linux).

I haven't gotten all the way to making sure the stack works on my VM, but it at least downloaded everything from git and appears to be properly structured.  I hope this helps in your troubleshooting.  It is definitely a work-around.  I am guessing the commands below will mean something to you -- I just googled until I figured out something to make this work.


// THIS IS THE COMMAND FROM THE GITHUB WIKI, BUT IT DOESN'T WORK:
// sudo pip install ansible debops passlib pycrypto
// IF I USE THE ANSIBLE INSTALLATION METHOD BELOW, IT SEEMS TO WORK JUST FINE


// ADD ANSIBLE TO THE PACKAGE REPO
sudo apt-add-repository ppa:ansible/ansible
[ENTER]

// REFRESH PACKAGE INDEX
sudo apt-get update
// INSTALL ANSIBLE
sudo apt-get install ansible


sudo pip install pycripto
sudo pip install passlib
sudo pip install debops

**Comment by Nilpo** [comment]
I tried this on several different OSes (Mac, Ubuntu, Centos). Installing Ansible from repo works fine, installing with pip generates the error above. I ended up doing essentially the same thing as @ejholdings.

@carlalexander You should update the documentation with the commands you suggested. Pip also generates a warning because it is outdated immediately after being installed.

**Comment by Nilpo** [comment]
@ejholdings Looking at your screenshot, you should be installing that on your local machine, not your server. The docs could be a little clearer about that as well. The current wording is slightly vague if you don't realize from the start that DebOps will be running locally and connecting to your server.

**Comment by harikrishnanr994** [comment]
This happened for many time in Digital Ocean Ubuntu 16.04 SSH using MacOS High Sierra.

fatal: [example.com]: FAILED! => {"changed": true, "cmd": ["wp", "core", "download"], "delta": "0:00:07.230066", "end": "2017-10-16 15:02:11.555465", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-10-16 15:02:04.325399", "stderr": "Error: Couldn't extract WordPress archive. unable to decompress gzipped phar archive \"/tmp/wp_59e4c9ed96898.tar.gz\" to temporary file", "stderr_lines": ["Error: Couldn't extract WordPress archive. unable to decompress gzipped phar archive \"/tmp/wp_59e4c9ed96898.tar.gz\" to temporary file"], "stdout": "Downloading WordPress 4.8.2 (en_US)...\nmd5 hash verified: 2e8744a702a3d9527782d9135a4c9544", "stdout_lines": ["Downloading WordPress 4.8.2 (en_US)...", "md5 hash verified: 2e8744a702a3d9527782d9135a4c9544"]}
	to retry, use: --limit @/Users/harihara/debops-wordpress/playbooks/wordpress.retry

**Comment by carlalexander** [comment]
Are you using `v0.4.1`? I added those packages in that release

**Comment by harikrishnanr994** [comment]
No `v0.4.0` There is only up to `v0.4.0`in your repo. Please add `v0.4.1`and update in your installation step. Thanks in advance

**Comment by carlalexander** [comment]
Thanks for the catch! Fixed 😄

**Comment by harikrishnanr994** [comment]
Hey @carlalexander I cant find the ``v0.4.1`` yet in the tags. Its not there in the repo yet.

```
debops-wordpress harihara$ git checkout tags/v0.4.1
error: pathspec 'tags/v0.4.1' did not match any file(s) known to git.
```

**Comment by carlalexander** [comment]
Should be good now!
