### ISSUE TITLE
Improve the installation process

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#11]
This is probably going to be a long-term discussion. The major hurdle comment so far has been around the [installation process](https://github.com/carlalexander/debops-wordpress/wiki/Installation). It's a hurdle that I thought good documentation might overcome. Once done, I haven't heard of any issues getting the rest to work.

I think it might be a good idea in the long run to create an install script and remove that friction. Or maybe the solution is to create a cli tool on top of DebOps similar to [EasyEngine](https://github.com/rtCamp/easyengine). Maybe we can try to find a way to extend the DebOps cli instead.

**Comment by drybjed** [comment]
I'm open to modfying the `debops*` scripts if necessary. Perhaps changing the CLI to something more like `git` syntax could benefit users more. Instead of `debops <ansible-playbook options>` we could switch to `debops play <ansible-playbook options>` and that would open more options... Not sure yet, but looking forward to discussion.

BTW, GItHub issues are not good discussion forum when you have multiple repositories - in that case participants must subscribe to all of them or miss something. If you want, you can use DebOps mailing list since it's mostly quiet anyway. I imagine more DebOps users would be interested in Wordpress solution and they just don't know about this repo. Just an idea though. :-)

**Comment by carlalexander** [comment]
Absolutely, I plan on coming along soon to discuss a few issues and tickets. I'm writing this down as I'm receiving feedback so I have a good idea where to focus next.  The DebOps command have worked well so far. The main issue is getting someone to a point that they can just run `debops -u root`.

The secondary issue is if we should offer more options through the `debops` cli since this is something good to bring upstream as well.

**Comment by carlalexander** [comment]
Closing in favour of [this](https://github.com/carlalexander/debops-wordpress/issues/214).
