### ISSUE TITLE
Varnish and frontend login

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#122]
Been trying to look for possible causes for this: i cannot use a frontend widget to login and came up short of an answer. 

Is somehow varnish config the culprit here?

**Comment by carlalexander** [comment]
Is this a built-in widget? I haven't tested something like this so it's possible.

**Comment by cezarneaga** [comment]
The theme has a frontend login. Is there a way to set varnish to allow it?

**Comment by carlalexander** [comment]
The problem is that in that scenario your front page isn't cached at all. Do you have a link to a demo site or something? I'd need to see how this form works.

**Comment by cezarneaga** [comment]
Dev.mhpss.net

**Comment by cezarneaga** [comment]
But if you want to test it take any buddypress website

**Comment by carlalexander** [comment]
Ok, I made an account and played around. I'm not sure it's a varnish issue or not. The login form doesn't use any cached data that I can see with Chrome dev tools.

If you try with a non-existing account, you'll see that the AJAX requests returns a payload with an error. If you try with a valid account, the payload is empty which I think is how they determine that the login was successful. In both cases, the `x-cache` header says `miss` which means it's not a cached response.

When the login is successful, the page reloads (this is good). But I think a step is broken, you're not getting any logged in cookies. I don't know where this is meant to happen in the theme, but that's the issue. 

If you reloaded with logged in cookies, you'd show as logged in. Since they never set any, you reload and you're still not logged in. If you try logging in elsewhere, it'll work fine because those cookies get set.

Now, I'm not dismissing that it isn't a Varnish problem. But I don't know or coudn't see where and when those cookies are set with the frontend login. That's what I'd look into and see if Varnish is at fault for not setting them.

**Comment by cezarneaga** [comment]
thanks for looking into it. the reason i suspected varnish is that on my local machine (mac with nginx webserver) it works. and that of my colleague (windows with LAMP).

**Comment by carlalexander** [comment]
Yeah, like I said, I'm at the limit of what I can detect from the browser. Have you tried shutting varnish off and seeing if that works?

**Comment by cezarneaga** [comment]
yeap. that just did it. works fine if i stop varnish

**Comment by carlalexander** [comment]
You're right. It's varnish. It's this directive that does it:

```
if (beresp.http.Set-Cookie && bereq.url !~ "wp-(login|admin)") {
  unset beresp.http.Set-Cookie;
}
```

I removes all `set-cookie` headers unless it's a URL with `wp-login` or `wp-admin` in it. Not sure, what's the best way to approach fixing this. It's not quite hardcoded, but it's considered a default directive so it's always added.

Because you want to allow any URL to use the `set-cookie` header, there's no need for this directive. That said, if we removed it, then cookies would be added anywhere which makes Varnish a lot less effective. Most visitors would get an uncached page due to cookies always being set.

In this context, maybe it's better to leave Varnish off? Otherwise, we can try to find a directive that will work. I'm just not sure Varnish will do much at that point.

**Comment by cezarneaga** [comment]
thanks carl!
it would be great to get this to work but i see how it may not :) be worth it. 

if login was a function of a certain page only? would it be possible then?
kind of: login happens only on /login and logout sends you to /logout

**Comment by carlalexander** [comment]
In that scenario, I'd say yes. 😄
