### ISSUE TITLE
wp-cli user

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#128]
Hi there,

i am trying to update wp core with wp-cli and get this message:
`Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress install exists under.`

any ideas/suggestions here?

**Comment by carlalexander** [comment]
You should be able to do it using `sudo -u wordpress wp <command>`. It'll be `www-data` instead of `wordpress` for older servers. You should also be to do it with your user, but I haven't looked at what it does to the permissions. 

But it's a good point, I need to look at making sure you can run wp-cli commands with your proper user without breaking anything.

**Comment by cezarneaga** [comment]
yeap. 
i tried `sudo -u www-data -i wp core update` and didnt work

**Comment by carlalexander** [comment]
You can't use `-i` with `www-data` as far as I know.

**Comment by cezarneaga** [comment]
now i know that :)
