### ISSUE TITLE
mod_pagespeed implementation

### ISSUE THREAD

**Issue by journeytosilius** [carlalexander/debops-wordpress#135]
I am kind of surprised that mod_pagespeed is not included in debops-wordpress. Is there any reason why ?

**Comment by carlalexander** [comment]
Good question! I looked into it a while ago. I couldn't see used by high-end hosts or [trellis](https://github.com/roots/trellis/issues/235) so I didn't put it in. But I think it's worth investigating a bit more after I'm done this release.

**Comment by journeytosilius** [comment]
I have successfully setup mod_pagespeed with nginx and Varnish, so it is possible. mod_pagespeed adds a layer of automated optimization that is hard to beat by anything else available ...

**Comment by wpbullet** [comment]
I remember looking into this a while ago and saw easyengine [dropped support](https://rtcamp.com/blog/easyengine-3-1-hhvm-pagespeed/#additional-notes-aboutpagespeed) for it because it wasn't working well or was assumed deprecated. On the[ modpagespeed github](https://github.com/pagespeed/mod_pagespeed) there has been updates so it may be worth a try. I will be sticking to my tried and tested tools though like tinyjpg and autoptimize.

**Comment by carlalexander** [comment]
Yeah, easy engine dropping it doesn't inspire confidence in it too much.

**Comment by carlalexander** [comment]
At this time, I don't think I'm going to implement this. The stack is pretty good as is. I don't want to add more complexity to it.
