### ISSUE TITLE
4000 seconds to complete debops-wordpress

### ISSUE THREAD

**Issue by JeffCleverley** [carlalexander/debops-wordpress#139]
It took 4000 seconds to complete debops-wordpress initially:

```
TASK: debops.ferm : Configure ip(6)tables rules ----------------------- 995.00s
TASK: debops.ferm : Configure ip(6)tables rules ----------------------- 971.34s
TASK: debops.fail2ban : Install custom fail2ban rule files ------------ 460.30s
TASK: debops.redis : Install Redis custom scripts --------------------- 107.32s
TASK: debops.postfix : Generate Postfix hash tables sources ----------- 265.55s
TASK: debops.fail2ban : Configure fail2ban jails ---------------------- 242.58s
TASK: debops.postfix : Generate Postfix tables sources ---------------- 232.88s
TASK: debops.nginx : Generate nginx server configuration -------------- 225.26s
TASK: debops.fail2ban : Configure custom fail2ban filters ------------- 168.16s
TASK: debops.nginx : Configure nginx upstreams ------------------------ 160.05s
TASK: debops.ferm : Remove ip(6)tables rules if requested ------------- 153.37s
TASK: debops.ferm : Make sure required directories exist --------------- 42.30s
```

I had issues with ansible version bug and fail2ban failing to restart too, so all in all it took a long time.

In your documentation it suggests 5 to 10 minutes, I understand ansible runs from laptop, but is this normal and or is there anyway to speed it up?

If I make changes to the Wordpress or Server configuration that need me to run debops-wordpress again, does it need to go through this entire process again?

**Comment by carlalexander** [comment]
Sorry to see this happen to you @JeffCleverley 😢 What's your latency to your server? Did you pick a geolocation close to you?

**Comment by JeffCleverley** [comment]
Hey @carlalexander, no problem really... it's an incredibly valuable tool you've made, so I wouldn't want to seem unappreciative.

I am in China, so there is that, but I did choose Singapore and I have 100/50 Mbit down/up. I did a separate run with my vpn on and Singaporean outlet server, but much the same. 

I actually deleted that droplet again (and big thanks for the $10 credit, yesterdays playing around cost all of 22c), as I want to customise the WordPress install as I usually would.

Am I right in thinking that when I do want to make changes to WP using debops, those that can be done to a running server, I will need to run through the complete `$ debops wordpress` process in full each time?

Not that it's such a problem, as long as I configure the server correctly at the beginning - I can make other changes on the fly with WP-CLi, probably more quickly given the latency I'm seeing.

**Comment by carlalexander** [comment]
Another workaround could be creating another droplet in Singapore and running Ansible from there. This is latency issue is an unfortunate side-effect of agentless server provisioning systems like Ansible.

You do have to run the process in full each time. I'd like it if there was a way to pre-prepare images ahead of time. (Maybe with `cloud-init`) I just don't know if it's possible. I haven't looked into it yet and I'm not sure what @drybjed does for his own servers.

**Comment by JeffCleverley** [comment]
That is an interesting proposition, use another droplet as the control machine... certainly worth thinking about if I decide to maintain my sites this way in the long-term.

Nice.

**Comment by drybjed** [comment]
There are multiple ways to apply partial changes to the hosts. All roles are tagged at the playbook level, so you can select a specific set of roles in the main playbook:
```
debops --limit <hostname> --tags role::nginx,role::nullmailer
```
You can check what tags are available by running command:
```
debops --list-tags
```
Each role has a corresponding playbook in the main `debops-playbooks` repository, you can use this playbook instead of the main playbook by specifying it as a first argument of the `debops` script:
```
debops service/mariadb_server --limit <hostname>
```
You can combine this with tags to further narrow down the configuration you want to change. For example, to modify the firewall configuration for the MariaDB server, you can run:
```
debops service/mariadb_server --limit <hostname> --tags role::ferm
```
Some roles have their own tags which allow you to apply partial configuration, as long as the whole role was applied on a host at least once, for example:
```
debops service/ferm --tags role::ferm:rules
```
To check what tags are available for a particular playbook, you can run:
```
debops service/ferm --list-tags
```
The above options are related to main DebOps playbook and roles, I'm not sure what @carlalexander added to DebOps for WordPress playbook.

**Comment by JeffCleverley** [comment]
Thanks @drybjed much appreciated
