### ISSUE TITLE
Recommend making default WordPress username something other than "admin"

### ISSUE THREAD

**Issue by shawnhooper** [carlalexander/debops-wordpress#15]
Either making this part of your configuration instructions to change it somewhere, or to make it another username that's stored in the secret folder along with the password.   "admin" is the old WordPress default username and is used in all sorts of automated attacks against WP sites.

**Comment by carlalexander** [comment]
I'm open to discussion on this. My decision to put `admin` as the default username was intentional. I figured I had two choices:
1. Force everyone to pick an admin username
2. Use `admin` as a default and help people change it in the future.

The first choice didn't seem appealing at the time (and still now to an extent). It adds a lot of additional step and learning curve to override the admin username. There's going to be situations (test servers, Vagrant, Docker) where that default is fine as well.

The second option seemed like the better choice. The goal is (once I get SSL working) to write a  "How to secure your server" guide. This will include changing the admin username, table prefix and all that good stuff.

**Comment by shawnhooper** [comment]
That makes sense.  The 2nd option, with the supporting documentation, is a reasonable solution.

**Comment by carlalexander** [comment]
Alright, documentation is done! You can find the part about the `admin` username [here](https://github.com/carlalexander/debops-wordpress/wiki/How-to-secure-your-WordPress-site#change-the-default-wordpress-username).
