### ISSUE TITLE
staging procedure: discussion

### ISSUE THREAD

**Issue by stefangweichinger** [carlalexander/debops-wordpress#157]
Aside from setting up the WP server, which is really helpful, I have to come up with some staging setup:

one server is test, the other production, and then I have to provide some mechanism to copy the content of $test to $prod. Back then I came up with some playbooks to pull/push mysql-content from/to the 2 machines, rsync files, edit $hostname in DB etc

Do you have any thoughts or plans to help doing this within this debops-role-set?

**Comment by ck1981** [comment]
Hello,

I'm not sure if this is helpful and may be stating the obvious however you could make use of WP-CLI which is included in debops-wordpress ie for dB operations such as changing hostname and doing exports/imports rather than using the tools they are built on ie mysqldump or scripting something yourself:

https://developer.wordpress.org/cli/commands/db/export/
https://developer.wordpress.org/cli/commands/import/

ie you can also use the below to replace your strings in the db ie hostname:

https://developer.wordpress.org/cli/commands/search-replace/

It is a long time since I did much with WP-CLI but you can probably use it to simplify your media operations too.

Otherwise you can go back to your familiar tools such as rsync etc and you may use the above with rsync/scp etc too obviously.

**Comment by stefangweichinger** [comment]
sorry for late reply, was on vacation. Thanks for suggestions. We are testing stuff like "WP-staging" and "duplicator" now to fit the customers needs (this on top of the debops-based machine).

**Comment by carlalexander** [comment]
Did @ck1981's advice help @stefangweichinger?

**Comment by carlalexander** [comment]
I'm going to close this for now. Feel free to reopen if you have other questions @stefangweichinger 😄
