### ISSUE TITLE
Do not make postfix dependent on hostname

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#26]
Not everyone will know how to make postfix work properly to send emails. Emails should always work whether someone set their hostname properly or not.

**Comment by drybjed** [comment]
Oh, I can't wait to see this :P

**Comment by carlalexander** [comment]
Yeah, I'm not sure if it can be done. I had someone contact me about an issue and I figured I'd put in a ticket to look into it. I'm thinking maybe I can parse the `wordpress_url` for the domain and pass it to postfix as the default instead.

**Comment by drybjed** [comment]
But for Postfix HELO/EHLO you don't want to use "some blog domain", you want to use the host FQDN, otherwise other SMTP servers, after checking if the hostname you gave in HELO is valid or not, might decide to block your mail. It's best to stick to the host FQDN or whatever the PTR lookup points to in this case. Which means DNS needs to be set up correctly for mails to work, there's no good workaround for that apart from a smarthost.

**Comment by carlalexander** [comment]
Oh, I see. So maybe, this needs to be a documentation issue. It needs to be clear that you need a good FQDN when creating the server. To be fair, I screwed that up at first too. I named my server `carlalexander-wordpress` and that caused a lot of issues.

**Comment by drybjed** [comment]
To be honest most of the DebOps roles depend on either `ansible_domain` or `ansible_fqdn` one way or the other, so I think that setting up a proper, resolvable domain should be a requirement. DebOps works on a single host without a domain for bootstrapping purposes, but don't expect everything to work in that case. Being a good netizen should be more important than screwing everybody else because your host is misconfigured.

**Comment by carlalexander** [comment]
I agree. Just looking at how best supporting that for anyone less familiar
with this. FQDN means nothing to most people who want to use this.

**Comment by carlalexander** [comment]
Not sure this is much of an issue anymore. We need `debops.mariadb` to have a valid FQDN to work so this shouldn't be an issue ever.
