### ISSUE TITLE
Allow completly seperate WP installations

### ISSUE THREAD

**Issue by ypid** [carlalexander/debops-wordpress#32]
I tested the multisite thing and that is not bad but it would also nice to have the option for completely separate wordpress installations. With the wpcli that should be double. Other things which need to be adjusted for this is the Varnish/Nginx setup. This is more a long term issue through.

**Comment by carlalexander** [comment]
This was discussed in #3. To do this in a secure manner, you need seperate fpm-pools, nginx users, etc. for each installation. This creates a proper separation between sites and prevents cross-contamination. It's a lot of work for a specific use case.

You can run a high performance site on a $5/month DO droplet which is quite cheap. I understand it's overkill for some and you could run multiple sites on that droplet. That said, I have no plans to support it in the near future.

Multisite is how large installations like wordpress.com work. I'd rather someone work that way. Otherwise, you should do the right thing and keep your installations on seperate servers.

**Comment by ypid** [comment]
All right. Maybe will implement it some day.

**Comment by carlalexander** [comment]
I'm going to close this for now. We can revisit this at another time.
