### ISSUE TITLE
Varnish DDoS Protection

### ISSUE THREAD

**Issue by tobeycodes** [carlalexander/debops-wordpress#33]
Would it be sensible to add something like this?

http://www.htpcguides.com/wordpress-ddos-attack-protection-varnish-4-firewall/

**Comment by carlalexander** [comment]
I saw that today! It might be a good idea. That said, when I load tested,
you could handle a huge amount of connections on the 5$/month droplet. But
could be cool.

**Comment by carlalexander** [comment]
I was thinking about it some more. I think it'd be good to protect certain non-cached pages as well like `/wp-login.php`.

**Comment by carlalexander** [comment]
Did some research on this today. My thought is that it would be better to have this at the firewall level using fail2ban. We'd scan the nginx access logs for the reverse proxy and ban based on that.

**Comment by carlalexander** [comment]
I'm thinking of three jails:
- One for bad bots using `apache-badbots` filter
- One that checks for excessive POST requests to `xmlrpc.php` and `wp-login.php`
- A generic DDOS that checks for excessive requests (limit to 1 per second)

That last one is the trickiest. Everything is going through the reverse proxy. We need to only check for page requests and maybe ignore assets. Maybe we need to tie it to the [nginx limit_req module](http://nginx.org/en/docs/http/ngx_http_limit_req_module.html) at the backend level.

**Comment by carlalexander** [comment]
We'll also look at writing documentation for integrating with the [wp-fail2ban](https://en-ca.wordpress.org/plugins/wp-fail2ban) plugin.

**Comment by carlalexander** [comment]
I've been working on this and there are a few issues that I found so far.
- The `wp-fail2ban` plugin doesn't work with HHVM. There seems to be a bug with the PHP `openlog` function which breaks the plugin.
- The default `ssh` jail doesn't work that well because [this issue](https://github.com/debops/ansible-rsyslog/issues/6). This also affects `wp-fail2ban`, but it doesn't matter that much because of the HHVM issue.

**Comment by carlalexander** [comment]
I also forgot. Another issue is that jails aren't permanent by default. If you restart fail2ban, you lose the bans (although I think they stick in the firewall). I'm thinking that it might be interesting to create a permanent jail for repeat offenders like [described here](https://wireflare.com/blog/permanently-ban-repeat-offenders-with-fail2ban/).

**Comment by carlalexander** [comment]
Just committed a lot of the work for this issue. `debops.fail2ban` is now a role dependency. It adds three jails (on top of the default ssh jail):
- `wordpress-badbots` which bans any badbot accessing the server immediately.
- `wordpress-ddos` which is a crude DDOS jail which bans anyone sending 300 requests (`GET` or `POST`) over 5 minutes. (Comes down to 1 request/sec)
- `wordpress-login` which bans anyone who sends more than 5 `POST` requests to `wp-login.php` or `xmlrpc.php` in a minute.

All bans are currently 2 hours. I have the jails active on my website and it will send me emails when it bans anyone. I'll monitor this over the next few weeks and make changes as it goes. 

The next step is making the permanent jail. I might leave it disabled by default. I'll think about it some more.

**Comment by carlalexander** [comment]
`wordpress-login` already doing its job. I might need the permanent jail sooner than later since I'm getting the same IP on the bans. I think with the permanent jail, I'll bring the ban time for `wordpress-login` to 10 minutes.

**Comment by carlalexander** [comment]
Added the `wordpress-permanent` jail just now. By default, it'll permaban anyone who receives 10 bans in the span of a week. 

This is a much more aggressive type of ban. It bypasses the firewall and bans the user at the routing table level. You have to unban them by hand afterwards since fail2ban won't keep track of the ban in the long term.

I also reduced the ban time for login attempts. It's now just a 10 minute ban. If someone wants to brute-force `wp-login.php` or `xmlrpc.php`. They'll just get permabanned in the span of two hours.

I think this is a good enough solution for this issue. I have email notifications for fail2ban turned on my server so I'll monitor for issues.
