### ISSUE TITLE
fails to complete 

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#78]
running `debops -u root` throws an error:

`TASK [debops.pki : Assert that required dependencies are met as documented] ****
fatal: [domainhere.com -> localhost]: FAILED! => {"assertion": "pki__register_bash_version.stdout | regex_replace(\"[^0-9.]\", \"\") | version_compare(\"4.3.0\", \">=\")", "changed": false, "evaluated_to": false, "failed": true}`

any idea how to fix this?

subsequently `debops wordpress -u root` throws this:
`TASK [debops.fail2ban : Configure custom fail2ban actions] *********************
fatal: [domainhere.com]: FAILED! => {"failed": true, "msg": "lookup plugin (template_src) not found"}`

cheers,
C

**Comment by carlalexander** [comment]
1) This is due to a [new change](https://github.com/debops/ansible-pki/pull/61) in `debops.pki` that came in 2 days ago. Right now, the only workaround would be to install an updated bash version using homebrew. I'll need to do a PR for it, but I'm on vacation in Spain at the moment.

2) This is a known issue with macOS. You can refer to the workaround [here](https://github.com/carlalexander/debops-wordpress/wiki/Known-issues#lookup-plugin-task_src-not-found). That should do the trick.

**Comment by cezarneaga** [comment]
ok. cool. 
have fun in your holiday. eat a chuleton for me too. :)

once you are back and find a fix would love to have a chat. i encountered a lot of issues and maybe we can find some solutions together.
best,
C

**Comment by carlalexander** [comment]
There should be a fix for the first problem already if you run debops-update.

**Comment by cezarneaga** [comment]
Solved it. the fix worked.
