### ISSUE TITLE
 [WARNING]: Optional dependency 'cryptography' raised an exception, falling back to 'Crypto'

### ISSUE THREAD

**Issue by matthew6688** [carlalexander/debops-wordpress#98]
Enviroment:  Mac OX 10.10.5
Server: Digital Ocean 14.4.5  x64

When i proceed to debops -u root

I show me:

`Running Ansible playbook from:
/Users/ringse/Library/Application Support/debops/debops-playbooks/playbooks/site.yml ...
 [WARNING]: Optional dependency 'cryptography' raised an exception, falling back
to 'Crypto'`

**Comment by uncheckederror** [comment]
I'm seeing this warning as well in a Debian Jessie environment.

**Comment by carlalexander** [comment]
Are you seeing this on your end @drybjed?

**Comment by matthew6688** [comment]
Fresh 16.04 Ubuntu from Digital Ocean shows the same message.

Running Ansible playbook from:
/Users/ringse/Library/Application Support/debops/debops-playbooks/playbooks/site.yml ...
 [WARNING]: Optional dependency 'cryptography' raised an exception, falling back
to 'Crypto'

**Comment by drybjed** [comment]
Are you using MacOS X? https://github.com/ansible/ansible/issues/16790

**Comment by sc-syf** [comment]
I met this warning when using ansible on ubuntu14.04.

First of all, when I run "sudo pip install ansible", it throw an exception, then I got a solution "sudo apt-get install libffi-dev" to fix this problem and installed ansible successful. 

I wrote my inventory file and ran "ansible all -m ping", I got the same warning above. so I used "sudo pip install cryptography"  fixed this warning.  hope it works for your problem.

**Comment by jwaibel** [comment]
you can remove python-cryptography to get rid of this warning

**Comment by sysarcher** [comment]
@jwaibel it got fixed for me when I installed the cryptography package using `pip`. @sc-syf sorry, I read your solution late...

Here's the log:-

``` bash
sudo pip install cryptography
Requirement already satisfied (use --upgrade to upgrade): cryptography in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.8 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/lib/python2.7/dist-packages (from cryptography)
Downloading/unpacking setuptools>=11.3 (from cryptography)
  Downloading setuptools-28.6.1-py2.py3-none-any.whl (471kB): 471kB downloaded
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography)
Installing collected packages: setuptools
  Found existing installation: setuptools 3.3
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed setuptools
Cleaning up...
```

Could `setuptools` be the issue?

**Comment by carlalexander** [comment]
I'm thinking of adding these two commands to the installation process for debops. Maybe they would help:

```
$ pip install --upgrade setuptools
$ pip install --upgrade pip
```

I still haven't seen this issue in my usage. Is it still happening?

**Comment by carlalexander** [comment]
I'm going to close this. If it's still happening, please reopen it!

**Comment by russellvt** [comment]
I see the same issue using ansible 2.1.2 with cryptography 1.5.2 (python 2.7.6 under Mint/Ubuntu). Doing an upgrade offers me 1.10.0 (after disqualifying a long list of "incompatible" versions of various dependencies, including setuptools). And then, the cffi dependency build fails...

So, looks like this is more-involved and, essentially, is "upgrade your environment." So, luckily I'm using [virtualenv](https://pypi.python.org/pypi/virtualenv)... and here's the long, drawn-out upgrade process to get this working.

Start by upgrading PIP from 1.5.4 to current (9.0.1 as-of this writing):

`pip install pip --upgrade`

This brings up [the familiar SNIMissingWarning and InsecurePlatformWarning in urllib3](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings). In the virtualenv, just install urllib3:

`pip install urllib3`

That should fix those issues (though there's always a chance that can be [more involved](https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2)). Now the upgrade breaks, missing pyparsing (and that module isn't available standalone). Fixed with setuptools...

`pip install setuptools`

Finally, you can upgrade the cryptography package...

`pip install cryptography --upgrade`

...and that will make that problem go away (at least on Python 2.7.6). As a final result, here's my full requirements.txt file:

> ansible==2.1.2.0
> appdirs==1.4.3
> asn1crypto==0.22.0
> cffi==1.9.1
> cryptography==1.8.1
> enum34==1.1.6
> idna==2.5
> ipaddress==1.0.18
> Jinja2==2.8
> MarkupSafe==0.23
> packaging==16.8
> paramiko==2.0.2
> pyasn1==0.1.9
> pycparser==2.17
> pycrypto==2.6.1
> pyparsing==2.2.0
> PyYAML==3.12
> six==1.10.0
> urllib3==1.20
